/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exam1P2_DanielElvir;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        DefaultComboBoxModel modelo
                = (DefaultComboBoxModel) PosicionJug.getModel();
        modelo.removeAllElements();
        modelo.addElement("Portero");
        modelo.addElement("Defensa");
        modelo.addElement("Medio Campista");
        modelo.addElement("Delantero");
        PosicionJug.setModel(modelo);

        DefaultComboBoxModel modelo1
                = (DefaultComboBoxModel) PieHabil.getModel();
        modelo1.removeAllElements();
        modelo1.addElement("Derecha");
        modelo1.addElement("Izquierda");
        PieHabil.setModel(modelo1);

        DefaultComboBoxModel modelo2
                = (DefaultComboBoxModel) PieHabil1.getModel();
        modelo2.removeAllElements();
        modelo2.addElement("Derecha");
        modelo2.addElement("Izquierda");
        PieHabil1.setModel(modelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        AgregarEquipo = new javax.swing.JPanel();
        NomEquipTXT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PaisEquipTXT = new javax.swing.JLabel();
        NomEquip = new javax.swing.JTextField();
        PaisEquip = new javax.swing.JTextField();
        AgregarEquipobttn = new javax.swing.JButton();
        AgregarEstadio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NomEstadTXT = new javax.swing.JLabel();
        NomCiudadTXT = new javax.swing.JLabel();
        NumCapacTXT = new javax.swing.JLabel();
        EstEquipTXT = new javax.swing.JLabel();
        NomEstad = new javax.swing.JTextField();
        NomCiudad = new javax.swing.JTextField();
        NumCapac = new javax.swing.JTextField();
        ListEquipos = new javax.swing.JComboBox<>();
        AgregarEstadioBttn = new javax.swing.JButton();
        AgregarJugador = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NomJug = new javax.swing.JTextField();
        EdadJug = new javax.swing.JTextField();
        NacionJug = new javax.swing.JTextField();
        PieHabil = new javax.swing.JComboBox<>();
        EquipoJug = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        PosicionJug = new javax.swing.JComboBox<>();
        AgregarJugadorBttn = new javax.swing.JButton();
        ListarJugador = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaJugador = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        ListarEquipos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEquipo = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        ListarEstadios = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaEstadio = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        NomJug1 = new javax.swing.JTextField();
        EdadJug1 = new javax.swing.JTextField();
        NacionJug1 = new javax.swing.JTextField();
        PieHabil1 = new javax.swing.JComboBox<>();
        cb_jugadores = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaJugador1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIFAAA SIUUUU");
        setResizable(false);

        jTabbedPane6.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane6StateChanged(evt);
            }
        });

        AgregarEquipo.setBackground(new java.awt.Color(102, 204, 255));

        NomEquipTXT.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        NomEquipTXT.setForeground(new java.awt.Color(0, 0, 0));
        NomEquipTXT.setText("Nombre del Equipo: ");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Agregar Equipo");

        PaisEquipTXT.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        PaisEquipTXT.setForeground(new java.awt.Color(0, 0, 0));
        PaisEquipTXT.setText("Pais del Equipo: ");

        AgregarEquipobttn.setBackground(new java.awt.Color(153, 0, 153));
        AgregarEquipobttn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        AgregarEquipobttn.setForeground(new java.awt.Color(0, 0, 0));
        AgregarEquipobttn.setText("Agregar Equipo");
        AgregarEquipobttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEquipobttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarEquipoLayout = new javax.swing.GroupLayout(AgregarEquipo);
        AgregarEquipo.setLayout(AgregarEquipoLayout);
        AgregarEquipoLayout.setHorizontalGroup(
            AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEquipoLayout.createSequentialGroup()
                .addGroup(AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarEquipoLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel2))
                    .addGroup(AgregarEquipoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PaisEquipTXT)
                            .addComponent(NomEquipTXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NomEquip)
                            .addComponent(PaisEquip, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))))
                .addContainerGap(503, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarEquipoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AgregarEquipobttn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );
        AgregarEquipoLayout.setVerticalGroup(
            AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEquipoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(59, 59, 59)
                .addGroup(AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomEquipTXT)
                    .addComponent(NomEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaisEquipTXT)
                    .addComponent(PaisEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(AgregarEquipobttn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Agregar Equipo", AgregarEquipo);

        AgregarEstadio.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Agregar Estadio");

        NomEstadTXT.setBackground(new java.awt.Color(0, 0, 0));
        NomEstadTXT.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        NomEstadTXT.setForeground(new java.awt.Color(0, 0, 0));
        NomEstadTXT.setText("Nombre del Estadio: ");

        NomCiudadTXT.setBackground(new java.awt.Color(0, 0, 0));
        NomCiudadTXT.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        NomCiudadTXT.setForeground(new java.awt.Color(0, 0, 0));
        NomCiudadTXT.setText("Nombre de la Ciudad: ");

        NumCapacTXT.setBackground(new java.awt.Color(0, 0, 0));
        NumCapacTXT.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        NumCapacTXT.setForeground(new java.awt.Color(0, 0, 0));
        NumCapacTXT.setText("Capacidad del Estadio: ");

        EstEquipTXT.setBackground(new java.awt.Color(0, 0, 0));
        EstEquipTXT.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        EstEquipTXT.setForeground(new java.awt.Color(0, 0, 0));
        EstEquipTXT.setText("Equipo al cual Pertenece el Estadio: ");

        ListEquipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AgregarEstadioBttn.setBackground(new java.awt.Color(153, 0, 153));
        AgregarEstadioBttn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        AgregarEstadioBttn.setForeground(new java.awt.Color(0, 0, 0));
        AgregarEstadioBttn.setText("Agregar Estadio");
        AgregarEstadioBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEstadioBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarEstadioLayout = new javax.swing.GroupLayout(AgregarEstadio);
        AgregarEstadio.setLayout(AgregarEstadioLayout);
        AgregarEstadioLayout.setHorizontalGroup(
            AgregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEstadioLayout.createSequentialGroup()
                .addGroup(AgregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarEstadioLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(AgregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NomCiudadTXT)
                            .addComponent(NumCapacTXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AgregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarEstadioLayout.createSequentialGroup()
                                .addComponent(NumCapac, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE))
                            .addGroup(AgregarEstadioLayout.createSequentialGroup()
                                .addComponent(NomCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(AgregarEstadioLayout.createSequentialGroup()
                        .addGroup(AgregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarEstadioLayout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addComponent(jLabel1))
                            .addGroup(AgregarEstadioLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(NomEstadTXT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NomEstad, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AgregarEstadioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(EstEquipTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarEstadioBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        AgregarEstadioLayout.setVerticalGroup(
            AgregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEstadioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(AgregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomEstadTXT)
                    .addComponent(NomEstad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(AgregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomCiudadTXT)
                    .addComponent(NomCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(AgregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumCapacTXT)
                    .addComponent(NumCapac, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AgregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarEstadioLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(AgregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EstEquipTXT)
                            .addComponent(ListEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarEstadioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(AgregarEstadioBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        jTabbedPane6.addTab("Agregar Estadio", AgregarEstadio);

        AgregarJugador.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Agregar Jugador");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre del Jugador: ");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Edad del Jugador: ");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nacionalidad del Jugador: ");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cual es el Pie Habil del Jugador: ");

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Equipo al que quiere que pertenezca: ");

        PieHabil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        EquipoJug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Posicion del Jugador:");

        PosicionJug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AgregarJugadorBttn.setBackground(new java.awt.Color(102, 0, 102));
        AgregarJugadorBttn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        AgregarJugadorBttn.setForeground(new java.awt.Color(0, 0, 0));
        AgregarJugadorBttn.setText("Agregar Jugador");
        AgregarJugadorBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarJugadorBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarJugadorLayout = new javax.swing.GroupLayout(AgregarJugador);
        AgregarJugador.setLayout(AgregarJugadorLayout);
        AgregarJugadorLayout.setHorizontalGroup(
            AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(269, 269, 269))
            .addGroup(AgregarJugadorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NomJug)
                    .addComponent(EdadJug)
                    .addComponent(NacionJug)
                    .addComponent(PieHabil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EquipoJug, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PosicionJug, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addComponent(AgregarJugadorBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        AgregarJugadorLayout.setVerticalGroup(
            AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarJugadorLayout.createSequentialGroup()
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AgregarJugadorLayout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(AgregarJugadorBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AgregarJugadorLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(NomJug, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(EdadJug, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(NacionJug, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(PieHabil, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(EquipoJug, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(PosicionJug, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Agregar Jugador", AgregarJugador);

        ListarJugador.setBackground(new java.awt.Color(0, 102, 102));

        listaJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Nacionalidad", "Pie Habil", "Equipo"
            }
        ));
        jScrollPane2.setViewportView(listaJugador);

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Listar Jugador");

        javax.swing.GroupLayout ListarJugadorLayout = new javax.swing.GroupLayout(ListarJugador);
        ListarJugador.setLayout(ListarJugadorLayout);
        ListarJugadorLayout.setHorizontalGroup(
            ListarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarJugadorLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarJugadorLayout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        ListarJugadorLayout.setVerticalGroup(
            ListarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarJugadorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Listar Jugador", ListarJugador);

        ListarEquipos.setBackground(new java.awt.Color(0, 102, 102));

        listaEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre del Equipo", "Pais del Equipo"
            }
        ));
        jScrollPane1.setViewportView(listaEquipo);

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Listar Equipos");

        javax.swing.GroupLayout ListarEquiposLayout = new javax.swing.GroupLayout(ListarEquipos);
        ListarEquipos.setLayout(ListarEquiposLayout);
        ListarEquiposLayout.setHorizontalGroup(
            ListarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarEquiposLayout.createSequentialGroup()
                .addContainerGap(404, Short.MAX_VALUE)
                .addGroup(ListarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarEquiposLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarEquiposLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(320, 320, 320))))
        );
        ListarEquiposLayout.setVerticalGroup(
            ListarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarEquiposLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Listar Equipos", ListarEquipos);

        ListarEstadios.setBackground(new java.awt.Color(0, 102, 102));

        listaEstadio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre del Estadio", "Ciudad", "Capacidad", "Equipo"
            }
        ));
        jScrollPane3.setViewportView(listaEstadio);

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Listar Estadios");

        javax.swing.GroupLayout ListarEstadiosLayout = new javax.swing.GroupLayout(ListarEstadios);
        ListarEstadios.setLayout(ListarEstadiosLayout);
        ListarEstadiosLayout.setHorizontalGroup(
            ListarEstadiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarEstadiosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(472, 472, 472))
            .addGroup(ListarEstadiosLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        ListarEstadiosLayout.setVerticalGroup(
            ListarEstadiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarEstadiosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Listar Estadios", ListarEstadios);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Modificar Jugador");

        jLabel21.setText("Seleccione el Jugador");

        jLabel22.setText("Nuevo Nombre:");

        jLabel23.setText("Nueva Edad: ");

        jLabel24.setText("Nueva Nacionalidad");

        jLabel25.setText("Nuevo Pie Habil:");

        PieHabil1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_jugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_jugadores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_jugadoresItemStateChanged(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Modificar El Jugador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NacionJug1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PieHabil1, 0, 231, Short.MAX_VALUE)
                        .addComponent(cb_jugadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(NomJug1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdadJug1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(420, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(416, 416, 416))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(399, 399, 399))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(cb_jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(NomJug1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(EdadJug1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NacionJug1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(PieHabil1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Modificar Jugador", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel26.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Modificar Equipo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(jLabel26)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel26)
                .addContainerGap(445, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Modificar Equipo", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("Modificar Estadio", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Eliminar Jugador");

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Seleccione el Jugador al que quiera Eliminar");

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Eliminar Jugador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listaJugador1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Nacionalidad", "Pie Habil", "Equipo"
            }
        ));
        jScrollPane4.setViewportView(listaJugador1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jButton1)))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane6.addTab("Eliminar Jugador", jPanel4);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Eliminar Estadio");

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Seleccione el Estadio al que quiera Eliminar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel15))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel18)))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addGap(29, 29, 29)
                .addComponent(jLabel18)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Eliminar Estadio", jPanel6);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Eliminar Equipo");

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Seleccione el Equipo al que quiera Eliminar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel19)))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Eliminar Equipo", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarEquipobttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEquipobttnActionPerformed
        equipos.add(new Equipo(NomEquip.getText(), PaisEquip.getText()));
        JOptionPane.showMessageDialog(this, "Equipo agregado exitosamente");
        NomEquip.setText("");
        PaisEquip.setText("");
    }//GEN-LAST:event_AgregarEquipobttnActionPerformed

    private void jTabbedPane6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane6StateChanged
        if (jTabbedPane6.getSelectedIndex() == 1) {
            ListEquipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
            for (Equipo t : equipos) {
                DefaultComboBoxModel modelo
                        = (DefaultComboBoxModel) ListEquipos.getModel();
                modelo.addElement(t);
                ListEquipos.setModel(modelo);
            }
        }

        if (jTabbedPane6.getSelectedIndex() == 2) {
            EquipoJug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
            for (Equipo t : equipos) {
                DefaultComboBoxModel modelo
                        = (DefaultComboBoxModel) EquipoJug.getModel();
                modelo.addElement(t);
                EquipoJug.setModel(modelo);
            }
        }

        if (jTabbedPane6.getSelectedIndex() == 3) {
            try {

                //limpiar tabla
                listaJugador.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Nombre", "Edad", "Nacionalidad", "Pie Habil", "Equipo"
                        }
                ));

                // TODO add your handling code here:            
                Equipo seleccionado = equipos.get(EquipoJug.getSelectedIndex());
                for (Jugador t : seleccionado.getPlantilla()) {
                    Object[] row = {t.getNombre(), t.getEdad(), t.getNacionalidad(), t.getPie_Habil(), t.getEquipo().toString()};
                    DefaultTableModel modelo = (DefaultTableModel) listaJugador.getModel();
                    modelo.addRow(row);
                    listaJugador.setModel(modelo);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

        if (jTabbedPane6.getSelectedIndex() == 4) {
            try {

                //limpiar tabla
                listaEquipo.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Nombre del Equipo", "Pais del Equipo",}
                ));

                // TODO add your handling code here:                        
                for (Equipo t : equipos) {
                    Object[] row = {t.getNombre(), t.getPais()};
                    DefaultTableModel modelo = (DefaultTableModel) listaEquipo.getModel();
                    modelo.addRow(row);
                    listaEquipo.setModel(modelo);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

        if (jTabbedPane6.getSelectedIndex() == 5) {
            try {

                //limpiar tabla
                listaEstadio.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Nombre del Estadio", "Ciudad", "Capacidad", "Equipo"
                        }
                ));

                // TODO add your handling code here:            
                for (Estadio t : estadios) {
                    Object[] row = {t.getNombre(), t.getCiudad(), t.getCapacidad(), t.getEquipo().toString()};
                    DefaultTableModel modelo = (DefaultTableModel) listaEstadio.getModel();
                    modelo.addRow(row);
                    listaEstadio.setModel(modelo);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

        if (jTabbedPane6.getSelectedIndex() == 6) {
            cb_jugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
            Equipo seleccionado = equipos.get(EquipoJug.getSelectedIndex());
            for (Jugador t : seleccionado.getPlantilla()) {

                DefaultComboBoxModel modelo
                        = (DefaultComboBoxModel) cb_jugadores.getModel();
                modelo.addElement(t);
                cb_jugadores.setModel(modelo);
            }
        }

        if (jTabbedPane6.getSelectedIndex() == 9) {
            try {

                //limpiar tabla
                listaJugador1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Nombre", "Edad", "Nacionalidad", "Pie Habil", "Equipo"
                        }
                ));

                // TODO add your handling code here:            
                Equipo seleccionado = equipos.get(EquipoJug.getSelectedIndex());
                for (Jugador t : seleccionado.getPlantilla()) {
                    Object[] row = {t.getNombre(), t.getEdad(), t.getNacionalidad(), t.getPie_Habil(), t.getEquipo().toString()};
                    DefaultTableModel modelo = (DefaultTableModel) listaJugador1.getModel();
                    modelo.addRow(row);
                    listaJugador1.setModel(modelo);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTabbedPane6StateChanged

    private void AgregarEstadioBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEstadioBttnActionPerformed
        try {
            estadios.add(new Estadio(NomEstad.getText(), NomCiudad.getText(), Integer.parseInt(NumCapac.getText()), (Equipo) ListEquipos.getSelectedItem()));
            JOptionPane.showMessageDialog(this, "Estadio Agregado exitosamente");
            NomEstad.setText("");
            NomCiudad.setText("");
            NumCapac.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error, contacte al administrador\n"
                    + "No se agregó nada");
        }

    }//GEN-LAST:event_AgregarEstadioBttnActionPerformed

    private void AgregarJugadorBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarJugadorBttnActionPerformed
        try {
            Equipo seleccionado = equipos.get(EquipoJug.getSelectedIndex());

            if (seleccionado.getPlantilla().size() < 4) {
                if (PosicionJug.getSelectedItem().toString().equalsIgnoreCase("Portero")) {
                    Equipo seleccion = equipos.get(EquipoJug.getSelectedIndex());
                    String nombre = NomJug.getText();
                    int Edad = Integer.parseInt(EdadJug.getText());
                    String Nacionalidad = NacionJug.getText();
                    Equipo equipo = (Equipo) EquipoJug.getSelectedItem();
                    seleccion.getPlantilla().add(new Portero(nombre, Edad, Nacionalidad, PieHabil.getSelectedItem().toString(), equipo));
                    JOptionPane.showMessageDialog(this, "Portero agregado exitosamente");
                } else if (PosicionJug.getSelectedItem().toString().equalsIgnoreCase("Defensa")) {
                    Equipo seleccion = equipos.get(EquipoJug.getSelectedIndex());
                    String nombre = NomJug.getText();
                    int Edad = Integer.parseInt(EdadJug.getText());
                    String Nacionalidad = NacionJug.getText();
                    Equipo equipo = (Equipo) EquipoJug.getSelectedItem();
                    seleccion.getPlantilla().add(new Portero(nombre, Edad, Nacionalidad, PieHabil.getSelectedItem().toString(), equipo));
                    JOptionPane.showMessageDialog(this, "Defensa agregado exitosamente");
                } else if (PosicionJug.getSelectedItem().toString().equalsIgnoreCase("Medio Campista")) {
                    Equipo seleccion = equipos.get(EquipoJug.getSelectedIndex());
                    String nombre = NomJug.getText();
                    int Edad = Integer.parseInt(EdadJug.getText());
                    String Nacionalidad = NacionJug.getText();
                    Equipo equipo = (Equipo) EquipoJug.getSelectedItem();
                    seleccion.getPlantilla().add(new Portero(nombre, Edad, Nacionalidad, PieHabil.getSelectedItem().toString(), equipo));
                    JOptionPane.showMessageDialog(this, "Medio Campista agregado exitosamente");
                } else if (PosicionJug.getSelectedItem().toString().equalsIgnoreCase("Delantero")) {
                    Equipo seleccion = equipos.get(EquipoJug.getSelectedIndex());
                    String nombre = NomJug.getText();
                    int Edad = Integer.parseInt(EdadJug.getText());
                    String Nacionalidad = NacionJug.getText();
                    Equipo equipo = (Equipo) EquipoJug.getSelectedItem();
                    seleccion.getPlantilla().add(new Portero(nombre, Edad, Nacionalidad, PieHabil.getSelectedItem().toString(), equipo));
                    JOptionPane.showMessageDialog(this, "Delantero agregado exitosamente");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ya no se puede agregar más jugadores a este equipo");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error, contacte al administrador\n"
                    + "No se agregó nada");
        }
    }//GEN-LAST:event_AgregarJugadorBttnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (listaJugador1.getSelectedRow() >= 0) {
            int r = JOptionPane.showConfirmDialog(listaJugador1, "Desea elimnar Jugador????", "Eliminar jugador", YES_NO_OPTION);
            if (r == 0) {
                DefaultTableModel modelo = (DefaultTableModel) listaJugador1.getModel();
                modelo.removeRow(listaJugador1.getSelectedRow());

                JOptionPane.showMessageDialog(this, "Se eliminó exitosamente");

            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar");
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_jugadoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_jugadoresItemStateChanged

    }//GEN-LAST:event_cb_jugadoresItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    ArrayList<Equipo> equipos = new ArrayList();
    ArrayList<Estadio> estadios = new ArrayList();
    ArrayList<Jugador> jugadores = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarEquipo;
    private javax.swing.JButton AgregarEquipobttn;
    private javax.swing.JPanel AgregarEstadio;
    private javax.swing.JButton AgregarEstadioBttn;
    private javax.swing.JPanel AgregarJugador;
    private javax.swing.JButton AgregarJugadorBttn;
    private javax.swing.JTextField EdadJug;
    private javax.swing.JTextField EdadJug1;
    private javax.swing.JComboBox<String> EquipoJug;
    private javax.swing.JLabel EstEquipTXT;
    private javax.swing.JComboBox<String> ListEquipos;
    private javax.swing.JPanel ListarEquipos;
    private javax.swing.JPanel ListarEstadios;
    private javax.swing.JPanel ListarJugador;
    private javax.swing.JTextField NacionJug;
    private javax.swing.JTextField NacionJug1;
    private javax.swing.JTextField NomCiudad;
    private javax.swing.JLabel NomCiudadTXT;
    private javax.swing.JTextField NomEquip;
    private javax.swing.JLabel NomEquipTXT;
    private javax.swing.JTextField NomEstad;
    private javax.swing.JLabel NomEstadTXT;
    private javax.swing.JTextField NomJug;
    private javax.swing.JTextField NomJug1;
    private javax.swing.JTextField NumCapac;
    private javax.swing.JLabel NumCapacTXT;
    private javax.swing.JTextField PaisEquip;
    private javax.swing.JLabel PaisEquipTXT;
    private javax.swing.JComboBox<String> PieHabil;
    private javax.swing.JComboBox<String> PieHabil1;
    private javax.swing.JComboBox<String> PosicionJug;
    private javax.swing.JComboBox<String> cb_jugadores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable listaEquipo;
    private javax.swing.JTable listaEstadio;
    private javax.swing.JTable listaJugador;
    private javax.swing.JTable listaJugador1;
    // End of variables declaration//GEN-END:variables
}
